# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build And Deploy For Testers"
  lane :testdeploy do
    # sh "your_script.sh"
    # You can also use other beta testing services here
    gradle(task: "clean assembleRelease")
    testupload
  end

  desc "Upload build to the server"
  lane :testupload do
    # sh "your_script.sh"
    scp(
        host: ENV["FASTLANE_UPLOAD_HOST"],
          username: ENV["FASTLANE_UPLOAD_USER"],
          upload: {
            src: "app/build/outputs/apk/release/app-release.apk",
            dst: ENV["FASTLANE_UPLOAD_HOST_FOLDER"] + "wv/wv.apk"
          }
     )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
